language: php
php:
  - 5.5
  - 5.6
  - hhvm
install:
  - composer install
script: phpunit --verbose --coverage-text --coverage-clover=/tmp/sphring/coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/sphring/coverage.clover
