<?php

namespace Sphring\MicroWebFramework\Model;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceInstanceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ServiceInstanceRepository extends EntityRepository
{
}
